/* ============================================================
PROJECT: Customer Analytics Report
AUTHOR: Vatsalya Prasad
LAYER: Gold (Analytics Layer)

OBJECTIVE
---------
Create a reusable customer analytics view that consolidates
customer behavior and key business metrics.

This report answers important business questions such as:

• Who are our most valuable customers?
• How frequently do customers purchase?
• How much revenue does each customer generate?
• How recently did customers place orders?
• What are the spending patterns of customers?

This view can be used by:
• Business analysts
• Data analysts
• BI dashboards
• Marketing teams


---------------------------------------------------------------
IMPORTANT ANALYTICAL CONCEPTS
---------------------------------------------------------------

DIMENSIONS
----------
Dimensions are descriptive attributes used to group,
filter, or categorize data.

Examples in this report:

customer_key
customer_number
customer_name
age
age_group
customer_segments
last_order_date


MEASURES
--------
Measures are numeric metrics that represent business
performance and can be aggregated.

Examples in this report:

total_orders
total_sales
total_quantity
total_products
avg_order_value
avg_monthly_spend
lifespan
recency

============================================================ */


/* ============================================================
DROP EXISTING VIEW IF IT EXISTS
Ensures the view can be recreated safely.
============================================================ */

IF OBJECT_ID('gold.customers_report', 'V') IS NOT NULL
    DROP VIEW gold.customers_report;
GO

/* ============================================================
CREATE CUSTOMER ANALYTICS VIEW

This view consolidates customer behaviour and performance
metrics derived from the sales fact table.
============================================================ */

CREATE VIEW gold.customers_report AS


/* ============================================================
STEP 1 — BASE QUERY

Purpose:
Retrieve detailed transaction-level data by joining
sales fact table with customer dimension.

This forms the foundation dataset used for aggregations.
============================================================ */

WITH base_query AS (

    SELECT
        f.order_number,
        f.product_key,
        f.order_date,
        f.sales_amount,
        f.quantity,
        c.customer_key,
        c.customer_number,

        -- Create a readable full customer name
        CONCAT(c.first_name, ' ', c.last_name) AS customer_name,

        -- Calculate current age of the customer
        DATEDIFF(YEAR, c.birthdate, GETDATE()) AS age

    FROM gold.fact_sales AS f

    LEFT JOIN gold.dim_customers c
        ON f.customer_key = c.customer_key

    -- Ignore records without order dates
    WHERE f.order_date IS NOT NULL
)



/* ============================================================
STEP 2 — CUSTOMER AGGREGATION

Purpose:
Aggregate transactional data at the customer level.

Metrics computed here summarize customer purchasing behavior.
============================================================ */

, customer_aggregation AS (

    SELECT
        customer_key,
        customer_number,
        customer_name,
        age,

        -- Number of unique orders placed by the customer
        COUNT(DISTINCT order_number) AS total_orders,

        -- Total revenue generated by the customer
        SUM(sales_amount) AS total_sales,

        -- Total number of items purchased
        SUM(quantity) AS total_quantity,

        -- Number of distinct products purchased
        COUNT(DISTINCT product_key) AS total_products,

        -- Most recent purchase date
        MAX(order_date) AS last_order_date,

        -- Customer lifecycle duration
        DATEDIFF(
            MONTH,
            MIN(order_date),
            MAX(order_date)
        ) AS lifespan

    FROM base_query

    GROUP BY
        customer_key,
        customer_number,
        customer_name,
        age
)



/* ============================================================
STEP 3 — FINAL CUSTOMER REPORT

Purpose:
Enhance aggregated data with business classifications
such as customer segments and age groups.
============================================================ */

SELECT

    /* --------------------------
       CUSTOMER DIMENSIONS
    --------------------------- */

    customer_key,
    customer_number,
    customer_name,
    age,

    -- Age segmentation
    CASE
        WHEN age < 20 THEN 'Under 20'
        WHEN age BETWEEN 20 AND 29 THEN '20 - 29'
        WHEN age BETWEEN 30 AND 39 THEN '30 - 39'
        WHEN age BETWEEN 40 AND 49 THEN '40 - 49'
        ELSE '50 and above'
    END AS age_group,


    /* --------------------------
       CUSTOMER SEGMENTATION
    --------------------------- */

    CASE
        WHEN total_sales > 5000 AND lifespan > 12
            THEN 'VIP'

        WHEN total_sales <= 5000 AND lifespan >= 12
            THEN 'Regular'

        ELSE 'New'
    END AS customer_segments,


    /* --------------------------
       CUSTOMER BEHAVIOR METRICS
    --------------------------- */

    last_order_date,

    -- Recency: months since last purchase
    DATEDIFF(
        MONTH,
        last_order_date,
        GETDATE()
    ) AS recency,


    /* --------------------------
       CUSTOMER MEASURES
    --------------------------- */

    total_orders,
    total_sales,
    total_quantity,
    total_products,
    lifespan,


    /* --------------------------
       DERIVED BUSINESS METRICS
    --------------------------- */

    -- Average Order Value (AOV)
    CASE
        WHEN total_sales = 0 THEN 0
        ELSE total_sales / total_orders
    END AS avg_order_value,


    -- Average Monthly Spend
    CASE
        WHEN lifespan = 0 THEN total_sales
        ELSE total_sales / lifespan
    END AS avg_monthly_spend

FROM customer_aggregation;

