/* ============================================================
PROJECT: Product Analytics Report
AUTHOR: Vatsalya Prasad
LAYER: Gold (Analytics Layer)

OBJECTIVE
---------
Create a reusable analytics view that summarizes product
performance using transactional sales data.

This report helps answer business questions such as:

• Which products generate the most revenue?
• Which products attract the most customers?
• How frequently are products sold?
• What is the average selling price of products?
• Which products are high-performing vs low-performing?

This report is designed for use by:
• Business Intelligence dashboards
• Data analysts
• Product managers
• Sales strategy teams


---------------------------------------------------------------
ANALYTICAL CONCEPTS USED
---------------------------------------------------------------

DIMENSIONS
----------
Dimensions describe the entities being analyzed.

Examples in this report:

product_key
product_name
category
subcategory
cost
product_segment
last_sale_date

These attributes help group or categorize product data.


MEASURES
--------
Measures are numerical metrics used to evaluate performance.

Examples in this report:

total_sales
total_orders
total_quantity
total_customers
avg_selling_price
avg_order_revenue
avg_monthly_revenue
lifespan
recency_in_months

Measures help quantify product performance.

============================================================ */


/* ============================================================
DROP EXISTING VIEW (IF IT EXISTS)

Ensures the view can be recreated safely.
============================================================ */

IF OBJECT_ID('gold.products_report', 'V') IS NOT NULL
    DROP VIEW gold.products_report;
GO


/* ============================================================
CREATE PRODUCT ANALYTICS VIEW
============================================================ */

CREATE VIEW gold.products_report AS


/* ============================================================
STEP 1 — BASE QUERY

Purpose:
Retrieve transaction-level product sales data by joining
the sales fact table with the product dimension.

This dataset will later be aggregated to calculate
product-level metrics.
============================================================ */

WITH base_query AS (

    SELECT
        f.order_number,
        f.order_date,
        f.customer_key,
        f.sales_amount,
        f.quantity,

        p.product_key,
        p.product_name,
        p.category,
        p.subcategory,
        p.cost

    FROM gold.fact_sales f

    LEFT JOIN gold.dim_products p
        ON p.product_key = f.product_key

    -- Ignore transactions with missing dates
    WHERE f.order_date IS NOT NULL
)



/* ============================================================
STEP 2 — PRODUCT AGGREGATIONS

Purpose:
Summarize key product metrics using the base dataset.

These aggregations help measure product popularity,
revenue generation, and customer engagement.
============================================================ */

, product_aggregations AS (

SELECT
    product_key,
    product_name,
    category,
    subcategory,
    cost,

    -- Product lifecycle (months between first and last sale)
    DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS lifespan,

    -- Most recent sale date
    MAX(order_date) AS last_sale_date,

    -- Number of unique orders containing the product
    COUNT(DISTINCT order_number) AS total_orders,

    -- Number of distinct customers who bought the product
    COUNT(DISTINCT customer_key) AS total_customers,

    -- Total revenue generated by the product
    SUM(sales_amount) AS total_sales,

    -- Total quantity sold
    SUM(quantity) AS total_quantity,

    -- Average selling price per item
    ROUND(
        AVG(
            CAST(sales_amount AS FLOAT) /
            NULLIF(quantity, 0)
        ),
    1) AS avg_selling_price

FROM base_query

GROUP BY
    product_key,
    product_name,
    category,
    subcategory,
    cost
)



/* ============================================================
STEP 3 — FINAL PRODUCT REPORT

Purpose:
Create the final product analytics dataset with
additional derived metrics and product segmentation.
============================================================ */

SELECT 

    /* --------------------------
       PRODUCT DIMENSIONS
    --------------------------- */

    product_key,
    product_name,
    category,
    subcategory,
    cost,



    /* --------------------------
       PRODUCT RECENCY METRICS
    --------------------------- */

    last_sale_date,

    -- Months since last sale
    DATEDIFF(
        MONTH,
        last_sale_date,
        GETDATE()
    ) AS recency_in_months,



    /* --------------------------
       PRODUCT SEGMENTATION
    --------------------------- */

    CASE
        WHEN total_sales > 50000 THEN 'High-Performer'
        WHEN total_sales >= 10000 THEN 'Mid-Range'
        ELSE 'Low-Performer'
    END AS product_segment,



    /* --------------------------
       PRODUCT PERFORMANCE MEASURES
    --------------------------- */

    lifespan,
    total_orders,
    total_sales,
    total_quantity,
    total_customers,
    avg_selling_price,



    /* --------------------------
       DERIVED BUSINESS METRICS
    --------------------------- */

    -- Average Order Revenue (AOR)
    CASE 
        WHEN total_orders = 0 THEN 0
        ELSE total_sales / total_orders
    END AS avg_order_revenue,


    -- Average Monthly Revenue
    CASE
        WHEN lifespan = 0 THEN total_sales
        ELSE total_sales / lifespan
    END AS avg_monthly_revenue

FROM product_aggregations;
